
#[derive(Debug)]
pub(crate) enum RTGException {
    // SECTION PLAYER
    RTG_PLAYER_ANIMATION_CANT_LOAD,
    RTG_PLAYER_ANIMATION_TEXTURE_ATLAS_CANT_LOAD,
    RTG_PLAYER_MOVEMENT_DELTA_TIME_INVALID,

    // SECTION ENEMY
    RTG_ENEMY_ANIMATION_TEXTURE_ATLAS_MISSING,
    RTG_ENEMY_MOVEMENT_ZERO_DIRECTION_VECTOR,

}